name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode latest
        run: sudo xcode-select -switch /Applications/Xcode_13.12.1.app

      - name: Build and Test
        run: xcodebuild clean build test -project FeedModule/FeedModule.xcodeproj -scheme "CI"
